language: java
before_install:
  - chmod +x gradlew

install: true

os: linux
jdk: openjdk11

script:
  - ./gradlew build --scan -s
  - ./gradlew test

after_success:
  - bash <(curl -s https://codecov.io/bash)